<?php

namespace HandMadeBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestNews($limit=null)
    {
        $query = $this->createQueryBuilder('n')
                ->select('n')
                ->addOrderBy('n.created','DESC');
        if (false === is_null($limit)){
            $query->setMaxResults($limit);
        }

        return $query->getQuery()->getResult();
    }
}
