<?php

namespace HandMadeBundle\Repository;
use Doctrine\ORM\Query;
use Gedmo\Translatable\TranslatableListener;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestNews($limit=null)
    {
        $query = $this->createQueryBuilder('n')
                ->select('n')
                ->addOrderBy('n.created','DESC');
        if (false === is_null($limit)){
            $query->setMaxResults($limit);
        }

        return $query->getQuery()->getResult();
    }

    public function findArticleByLocale($locale, $id)
    {
        $queryBuilder = $this->createQueryBuilder("a");

        $queryBuilder
                ->select('a')
            ->where("a.id = :id")
            ->setParameter('id', $id)
        ;

        $query = $queryBuilder->getQuery();

        $query->setHint(
            Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        $query->setHint(TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale);

        return $query->getResult();
    }
}
