<?php

namespace HandMadeBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestProducts($limit=null)
    {
        $query = $this->createQueryBuilder('p')
                ->select('p')
                ->addOrderBy('p.created','DESC');
        if (false === is_null($limit)){
            $query->setMaxResults($limit);
        }

        return $query->getQuery()->getResult();
    }
}
